# Usar a imagem oficial do Postgres com base Alpine
FROM postgres:15-alpine

# Atualizar repositórios e instalar locale support
RUN apk update && apk add --no-cache musl-locales musl-locales-lang
