version: '3.8'

services:
  langflowai:
    build:
      context: .
      dockerfile: Dockerfile.langflow
    restart: unless-stopped
    command: uvicorn langflow.main:create_app --host 0.0.0.0 --port 7860 --workers 4
    environment:
      # --- VARIÁVEIS DE AUTENTICAÇÃO ---
      - LANGFLOW_NEW_USER_IS_ACTIVE=true
      - LANGFLOW_SUPERUSER=${LANGFLOW_SUPERUSER}
      - LANGFLOW_SUPERUSER_PASSWORD=${LANGFLOW_SUPERUSER_PASSWORD}

      # --- VARIÁVEIS DE IDIOMA E TIMEZONE ---
      - TZ=America/Sao_Paulo
      - LANG=pt_BR.UTF-8
      - LANGUAGE=pt_BR:pt:en
      - LC_ALL=pt_BR.UTF-8

      # --- VARIÁVEIS DA APLICAÇÃO ---
      - LANGFLOW_DATABASE_URL=${LANGFLOW_DATABASE_URL}
      - LANGFLOW_CACHE_TYPE=redis
      - LANGFLOW_REDIS_URL=${LANGFLOW_REDIS_URL}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_REGION=auto
    depends_on:
      - postgres
      - redis
    networks:
      - sua_rede_backend # Use a mesma rede dos outros serviços

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      # Variáveis de Fuso Horário e Idioma
      - TZ=America/Sao_Paulo
      - LANG=pt_BR.UTF-8
      - LANGUAGE=pt_BR:pt:en
      - LC_ALL=pt_BR.UTF-8

      # Variáveis do Banco de Dados
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sua_rede_backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - sua_rede_backend

volumes:
  postgres_data: {}

networks:
  sua_rede_backend:
    # ...